"""possibly adding vitamin column

Revision ID: 2a4d70b52d3d
Revises: 3724968dbf43
Create Date: 2025-02-17 17:06:22.077620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a4d70b52d3d'
down_revision = '3724968dbf43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vitamin')
    op.drop_table('product_vitamin')
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vitamin', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('vitamin')

    op.create_table('product_vitamin',
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.Column('vitamin_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['vitamin_id'], ['vitamin.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'vitamin_id')
    )
    op.create_table('vitamin',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###
